### ISSUE TITLE
Add Table of Contents

### ISSUE THREAD

**Issue by vandesai1** [fornax-navo/fornax-documentation#14]
It would be great to have a dynamically-generated table of contents for the Fornax Science Console User Guide.

**Comment by bsipocz** [comment]
I haven't yet found a solution for auto-generating the TOC, all suggestions points to manually linking to the headings. 
(Note: this only affects the markdown rendering on the github repo landing page, for the HTML version of the documentation we already auto-generate from the headings using the ``{toctree}`` directive)

**Comment by vandesai1** [comment]
Can you point to the HTML version of the documentation? I am accustomed to looking here:

https://fornax-navo.github.io/fornax-documentation/

**Comment by bsipocz** [comment]
We currently do TOC on the landing page (there is a bug with a duplicated heading, currently it's  https://fornax-navo.github.io/fornax-demo-notebooks/#id1)

The full rendering is here: https://fornax-navo.github.io/fornax-demo-notebooks/documentation/README.html where the TOC lands as a sidebar, so I don't think it's necessary to duplicate it at the top of the document, but we can do it if you think it's useful.
I've also asked around if someone found a solution for auto getenate it on the github view.

**Comment by bsipocz** [comment]
I got an answer already (thanks Hugo!), that it cannor be done with md files, however github does generate one that is accessible with the icon right to the edit icon:

<img width="1293" alt="Screenshot 2024-04-15 at 14 05 54" src="https://github.com/fornax-navo/fornax-documentation/assets/6788290/7d0d7f0c-7c43-418f-baae-b0b2dd9024fb">

**Comment by vandesai1** [comment]
Ah, thank you! I don't think I ever scrolled down far enough on https://fornax-navo.github.io/fornax-demo-notebooks/ to notice the documentation there! It's perhaps a little confusing that there are two headings for Documentation.

Do you think it would make sense to get rid of:
![image](https://github.com/fornax-navo/fornax-documentation/assets/26556144/f05d8e9b-95a6-4cfb-b28f-96fc0f68a24f)

**Comment by bsipocz** [comment]
> Do you think it would make sense to get rid of:

yes, that's the bug, and I'm on it with this PR: https://github.com/fornax-navo/fornax-demo-notebooks/pull/272

**Comment by jkrick** [comment]
It looks like this has been done as best as possible, nothing works perfectly with CI for this situation.  The end user will likely never have this problem, so I will close this for now.  We can always re-open if necessary.
