### ISSUE TITLE
Draft answers to technical questions for documentation

### ISSUE THREAD

**Issue by jkrick** [fornax-navo/fornax-documentation#3]
Unanswered questions in the documentation need answers.  Anything without an answer means that I don't know the answer.  Please either add an answer, or remove the question if you feel it is not useful for users. There are a couple of these in each of the sections. but no obvious way to group them.

**Comment by jkrick** [comment]
just pinging @trjaffe and @zoghbi-a that I still need help with the answers to some of the documentation questions.

**Comment by zoghbi-a** [comment]
Thanks @jkrick for gathering those questions. The answer to many of them are still being worked out.
The development team has changed, and that slowed the dev work a little, but hopefully it is more organized now, and we'll start getting the answers soon.

**Comment by trjaffe** [comment]
I answered a few and did a super quick PR.

**Comment by vandesai1** [comment]
Closing this issue and will create new issues with specific requests.
