### ISSUE TITLE
Convert markdown to HTML

### ISSUE THREAD

**Issue by jkrick** [fornax-navo/fornax-documentation#5]
This is one markdown document currently, but would be nice to have an HTML document that looks good.  I don't know how to do this.

One suggestion from @bsipocz is the following example: https://epyc.astro.washington.edu/~bsipocz/fornax/html/#more-details-about-the-fornax-portal  (this link is not permanent).
- this puts the documentation at the bottom of the website which houses the rendered notebooks under a heading of "More details about the Fornax Portal"
- Do we want it to also be a standalone document?  if so, where?  Do we have main landing page already (similar to heliocloud.org)?
- Do we have control over the number of headings that the page shows?  ie., currently there is a main heading of "Fornax Science Console" then under that there is "Getting Started", "Data access", etc.  Can we also have the individual questions listed under each section?  ie., under "Getting Started" list out also "How do I get an account/.", "How to login?" etc.,   I like to have a fuller table of contents so I can scan for my individual problem before being directed to the long document with everything in it (which makes scanning more difficult).  Scanning here means either by eye or with a text search.

**Comment by bsipocz** [comment]
> this puts the documentation at the bottom of the website which houses the rendered notebooks under a heading of "More details about the Fornax Portal"

Location can be anywhere, we have full control over it, I just happened to add it to the bottom of the page.

**Comment by bsipocz** [comment]
One thing maybe worth to consider: cutting up the currenly one single md file into separate ones. The HTML can still show one or multiple of those as one page, but it would also allow better segmentation to sub pages.

**Comment by bsipocz** [comment]
This has been done. There is a temporary bug due to the duplicated `#Documenation` heading, but it will be fixed upsteam, so I'm closing this issue now as done.

Link to the section on the landing page will be https://fornax-navo.github.io/fornax-demo-notebooks/#documentation
with the content here: https://fornax-navo.github.io/fornax-demo-notebooks/documentation/README.html

(currently the landing URL is https://fornax-navo.github.io/fornax-demo-notebooks/#id1)
